import { SongHash } from "./PlaylistSongs";

export type PlaylistQueue = PlaylistQueueItem[];

export interface PlaylistQueueItem {
  // generated by Firebase
  id?: string,

  songHash: SongHash;
  addedTime: Timestamp;
}
